### ISSUE TITLE
mod_powのバグ

### ISSUE THREAD

**Issue by ei1333** [Luzhiled/syakyo-library#5]
mod が 1 のときでも 1 を返してしまう

https://github.com/Luzhiled/syakyo-library/blob/6b480f1c91b16eaa614c7645bd026c6ce38654b3/src/math/modular-arithmetic/mod-pow.hpp#L8

**Comment by Luzhiled** [comment]
これ忘れてたわ、ありがとう

**Comment by ei1333** [comment]
いや、やっぱ忘れたままでいいや

**Comment by Luzhiled** [comment]
最後に mod とればいいか…………
